"""ortus human <repo> — emit HUMAN-TODO.md for human-flagged bd issues (idzn.3).

Strictly read-only from bd's perspective (NFR-006). Only HUMAN-TODO.md is
written. Renders pros/cons option markers when present in the latest
comment of a flagged issue.
"""

from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path
from typing import Iterable, Optional

import typer

from ortus.core import output
from ortus.core.bd import BdClient
from ortus.core.repo import resolve_repo


OPTION_RE = re.compile(r"^\*\*Option\s+(\d+)[:\s]*\*\*\s*(.*)$", re.MULTILINE)


def _render_options(text: str) -> str | None:
    """If `text` contains '**Option N:**' markers, render them as a list."""
    matches = list(OPTION_RE.finditer(text))
    if not matches:
        return None
    out = ["", "**Structured options:**", ""]
    for m in matches:
        n, head = m.group(1), m.group(2).strip()
        out.append(f"- **Option {n}** — {head}")
    out.append("")
    return "\n".join(out)


def _truncate(text: str, limit: int = 2048) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + "\n\n[... truncated; bd show <id> for full]"


def _summary(text: str, limit: int = 200) -> str:
    collapsed = " ".join(text.split())
    return collapsed[:limit]


def _render_issue(issue: dict, comments: list[dict]) -> str:
    issue_id = issue["id"]
    title = issue.get("title", "")
    priority = issue.get("priority", "?")
    status = issue.get("status", "?")
    description = issue.get("description", "") or ""
    parent = issue.get("parent")

    out: list[str] = []
    out.append(f"## {issue_id} — {title}  [P{priority}, {status}]")
    if parent:
        out.append(f"_Parent: {parent}_")
    out.append("")

    if comments:
        latest = sorted(comments, key=lambda c: c.get("created_at", ""))[-1]
        text = _truncate(latest.get("text", ""))
        ts = latest.get("created_at", "?")
        author = latest.get("author", "?")
        out.append(f"**Why blocked:** {_summary(text)}")
        out.append("")
        out.append(f"**Last comment** ({ts}, {author}):")
        out.extend(f"> {line}" for line in text.splitlines())
        options = _render_options(text)
        if options:
            out.append(options)
    elif description:
        out.append(f"**Description:** {_summary(description)}")
    else:
        out.append("(no comments, no description)")
    out.append("")
    return "\n".join(out)


def _render_report(issues: list[dict], client: BdClient) -> str:
    today = _dt.date.today().isoformat()
    header = [
        "# Human-decision queue",
        "",
        f"_Generated by `ortus human` on {today}; do not edit (regenerated each run)._",
        "",
        f"**Open human-flagged issues:** {len(issues)}",
        "",
    ]
    if not issues:
        return "\n".join(header + ["No issues are currently flagged for human review.", ""])
    body: list[str] = []
    for issue in issues:
        comments = client.comments(issue["id"])
        body.append(_render_issue(issue, comments))
    return "\n".join(header + body)


def human(
    repo: Optional[Path] = typer.Argument(
        None, help="Target repo directory. Defaults to $PWD; no walk-up."
    ),
    no_file: bool = typer.Option(
        False, "--no-file", help="Print report to stdout; don't write HUMAN-TODO.md."
    ),
) -> None:
    """Render HUMAN-TODO.md from bd issues flagged for a human decision."""
    target = resolve_repo(repo)
    client = BdClient(target)
    issues = client.list_human()
    report = _render_report(issues, client)
    if no_file:
        output.info(report)
        return
    out_path = target / "HUMAN-TODO.md"
    out_path.write_text(report)
    output.success(f"wrote {out_path.relative_to(target)} ({len(issues)} issue(s))")
